os:
- linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test

env:
- VERSION=4.8
- VERSION=4.9
- VERSION=5
- VERSION=6
- VERSION=7
- VERSION=8

language: python
python:
# subprocess.check_output is required, and only available starting 2.7, so
# don't include 2.6.
# - "2.6"
- "2.7"
- "3.3"
- "3.4"
- "3.5"
- "3.6"

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq g++-$VERSION gcc-$VERSION-plugin-dev

install:
  - pip install six pygments graphviz lxml

script: make CC=gcc-$VERSION CXX=g++-$VERSION
